---
# NOTE: this file is managed by terraform

name: pre-commit

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - test-*

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  HADOLINT_VERSION: 'v2.12.0'
  PRE_COMMMIT_VERSION: '4.2.0'
  PYSCAN_RS_VERSION: '0.1.7'
  PYTHON_VERSION: '3.13.2'
  TERRAFORM_VERSION: '1.11.3'
  TFLINT_VERSION: 'v0.55.1'

permissions:
  contents: read

jobs:
  default-run:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install pre_commit==${{ env.PRE_COMMMIT_VERSION }} pyscan-rs==${{ env.PYSCAN_RS_VERSION }}

    - name: Pyscan vulnerabilities on python dependencies
      run: |
        # pyscan on python dependencies
        [[ ! -f "requirements.txt" && ! -f "pyproject.toml" ]] || pyscan -d .

    - name: Install hadolint
      run: |
        wget -O hadolint https://github.com/hadolint/hadolint/releases/download/${{ env.HADOLINT_VERSION }}/hadolint-Linux-x86_64
        chmod +x hadolint
        sudo mv hadolint /usr/bin/
        hadolint --version

    - name: Install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Install tflint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: ${{ env.TFLINT_VERSION }}

    - name: Run pre-commit on everything
      run: pre-commit run -a -v

  add-on-checkov:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run Checkov Github Action
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        log_level: WARNING
        quiet: false
        skip_results_upload: "true"
        enable_secrets_scan_all_files: "true"
        skip_check: CKV_GIT_1,CKV_GIT_3,CKV_GIT_5,CKV_GIT_6,CKV2_GIT_1,CKV2_GHA_1,CKV_DOCKER_2,CKV_DOCKER_3
        # Skip Check Details
        # ID           Description
        # CKV_GIT_1    - Ensure GitHub repository is Private
        # CKV_GIT_3    - Ensure GitHub Repository defined in Terraform have vulnerability alerts enabled
        # CKV_GIT_5    - Ensure GitHub pull requests should require at least 2 approvals
        # CKV_GIT_6    - Ensure GitHub branch protection rules requires signed commits
        # CKV2_GIT_1   - Ensure each Repository has branch protection associated
        # CKV2_GHA_1   - Ensure top-level permissions are not set to write-all
        # CKV_DOCKER_2 - Ensure that HEALTHCHECK instructions have been added to container images
        # CKV_DOCKER_3 - Ensure that a user for the container has been created
